{% set name = "grabseqs" %}
{% set version = "0.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/yumyai/grabseqs.git
  git_rev: HEAD
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 0
  entry_points:
    - grabseqs = grabseqslib:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pandas
    - python {{ python }}
    - requests
    - requests_html
  run:
    - pandas
    - python
    - requests
    - requests_html
    - sra-tools
    - pigz
    - wget

test:
  imports:
    - grabseqslib
  commands:
    - grabseqs --help

about:
  home: "https://github.com/yumyai/grabseqs"
  license: MIT
  license_family: MIT
  summary: "Easily download reads from next-gen sequencing repositories like NCBI SRA"

extra:
  recipe-maintainers:
    - yumyai
